// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4saB12Sp2-7WbPOmyY6-hHPgu9f79Lk4',
    appId: '1:881248571092:web:d3401783e02ea6b6b73541',
    messagingSenderId: '881248571092',
    projectId: 'flutter-lab-firebas-4f04d',
    authDomain: 'flutter-lab-firebas-4f04d.firebaseapp.com',
    storageBucket: 'flutter-lab-firebas-4f04d.appspot.com',
    measurementId: 'G-MM5DEJXC8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCky4HdEVRvomnNe7qWyeMGfLL4ABJFCZU',
    appId: '1:881248571092:android:9e2e76a257de71a8b73541',
    messagingSenderId: '881248571092',
    projectId: 'flutter-lab-firebas-4f04d',
    storageBucket: 'flutter-lab-firebas-4f04d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcOWG7kr2nwlfqbwf_wWN0jjKynd5oZTY',
    appId: '1:881248571092:ios:12e57a4342c0fccbb73541',
    messagingSenderId: '881248571092',
    projectId: 'flutter-lab-firebas-4f04d',
    storageBucket: 'flutter-lab-firebas-4f04d.appspot.com',
    iosClientId: '881248571092-602hmtn6620rr75dhunru15upo7rkqv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabFirebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcOWG7kr2nwlfqbwf_wWN0jjKynd5oZTY',
    appId: '1:881248571092:ios:12e57a4342c0fccbb73541',
    messagingSenderId: '881248571092',
    projectId: 'flutter-lab-firebas-4f04d',
    storageBucket: 'flutter-lab-firebas-4f04d.appspot.com',
    iosClientId: '881248571092-602hmtn6620rr75dhunru15upo7rkqv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabFirebas',
  );
}
